apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-fsx-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-fsx-sc
  mountOptions:
    - flock
  nfs:
    path: "/fsx"
    server: "fs-0db52d44e7149d9f9.fsx.us-east-1.amazonaws.com"
